# App
spring.application.name=smart-uni-api
server.port=8080

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=smart_uni_db

# JWT
app.jwt.secret=${JWT_SECRET:change-me-to-a-long-random-secret-value-here}
app.jwt.expiration-ms=86400000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# Mongo / audit
spring.data.mongodb.auto-index-creation=true

# Logging
logging.level.org.springframework=INFO
logging.level.org.springframework.security=INFO
logging.level.com.smartuni.api=DEBUG
logging.level.com.smartuni=DEBUG

#Forgor Password reset email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true